# Generated by Django 3.1.5 on 2021-01-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customer_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                (
                'customer_title', models.CharField(default='', max_length=200, verbose_name='Название для покупателя')),
            ],
        ),
        migrations.CreateModel(
            name='MacroProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                (
                'customer_title', models.CharField(default='', max_length=200, verbose_name='Название для покупателя')),
            ],
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                (
                'customer_title', models.CharField(default='', max_length=200, verbose_name='Название для покупателя')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='internal_id',
            field=models.IntegerField(default=-1, verbose_name='ID из внутренней базы'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                (
                'customer_title', models.CharField(default='', max_length=200, verbose_name='Название для покупателя')),
                ('content_option',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_interface.contentoption',
                                   verbose_name='Вариант содержимого')),
                ('macro_product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_interface.macroproduct',
                                   verbose_name='Макротовар')),
                ('menu_item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_interface.menu',
                                   verbose_name='Товар из меню 1С')),
                ('size_option',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_interface.sizeoption',
                                   verbose_name='Вариант размера')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                (
                'customer_title', models.CharField(default='', max_length=200, verbose_name='Название для покупателя')),
                ('menu_item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_interface.menu',
                                   verbose_name='Товар из меню 1С')),
                ('product_variants',
                 models.ManyToManyField(to='customer_interface.ProductVariant', verbose_name='Вариант товара')),
            ],
        ),
    ]
