# Generated by Django 3.1.5 on 2021-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_interface', '0002_auto_20210127_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroproduct',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
