# Generated by Django 3.1.5 on 2021-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_interface', '0003_macroproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroproduct',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/category_pictures', verbose_name='Иконка'),
        ),
    ]
