# Generated by Django 3.1.5 on 2021-02-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_interface', '0004_macroproduct_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentoption',
            name='internal_id',
            field=models.IntegerField(default=-1, verbose_name='ID из внутренней базы'),
        ),
        migrations.AddField(
            model_name='contentoption',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/content_pictures', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='macroproduct',
            name='internal_id',
            field=models.IntegerField(default=-1, verbose_name='ID из внутренней базы'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='internal_id',
            field=models.IntegerField(default=-1, verbose_name='ID из внутренней базы'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='internal_id',
            field=models.IntegerField(default=-1, verbose_name='ID из внутренней базы'),
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='internal_id',
            field=models.IntegerField(default=-1, verbose_name='ID из внутренней базы'),
        ),
    ]
