# Generated by Django 3.1.5 on 2021-02-03 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('customer_interface', '0005_auto_20210202_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='avg_preparation_time',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='note',
        ),
    ]
