# Generated by Django 3.1.5 on 2021-02-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customer_interface', '0007_macroproduct_customer_appropriate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroProductContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                (
                'customer_title', models.CharField(default='', max_length=200, verbose_name='Название для покупателя')),
                ('slug', models.SlugField(default='', unique=True)),
                ('picture',
                 models.ImageField(blank=True, null=True, upload_to='img/category_pictures', verbose_name='Иконка')),
                ('customer_appropriate',
                 models.BooleanField(default=False, verbose_name='Подходит для демонстрации покупателю')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='content_option',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='macro_product',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='macro_product_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='customer_interface.macroproductcontent', verbose_name='Содержимое макротовара'),
        ),
    ]
