# Generated by Django 3.1.5 on 2021-03-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_interface', '0010_macroproductcontent_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meat_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес мяса в товаре'),
        ),
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес товара'),
        ),
    ]
