# Generated by Django 3.1.5 on 2021-03-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0011_auto_20210314_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroproductcontent',
            name='internal_id',
            field=models.IntegerField(default=-1, verbose_name='ID из внутренней базы'),
        ),
    ]
