# Generated by Django 3.1.5 on 2022-06-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0012_macroproductcontent_internal_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macroproduct',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='macroproduct',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='ordering'),
        ),
    ]
