# Generated by Django 3.1.5 on 2022-07-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0013_auto_20220630_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='content_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_interface.contentoption', verbose_name='Вариант содержимого'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='macro_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer_interface.macroproduct', verbose_name='Макротовар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_interface.sizeoption', verbose_name='Вариант размера'),
        ),
    ]
