# Generated by Django 3.1.5 on 2022-07-06 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0015_auto_20220706_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroproductcontent',
            name='macro_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='customer_interface.macroproduct', verbose_name='Макротовар'),
        ),
    ]
