# Generated by Django 3.1.5 on 2022-10-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0019_menu_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.TextField(default='', verbose_name='data'),
        ),
    ]
