# Generated by Django 3.1.5 on 2022-10-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0021_auto_20221014_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='macro_product_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='customer_interface.macroproductcontent', verbose_name='Содержимое макротовара'),
        ),
    ]
