# Generated by Django 3.1.5 on 2023-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0024_auto_20231116_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='guid_1c',
        ),
        migrations.AlterField(
            model_name='macroproduct',
            name='customer_appropriate',
            field=models.BooleanField(default=False, help_text='виден покупателю на сайте', verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='macroproductcontent',
            name='customer_appropriate',
            field=models.BooleanField(default=False, help_text='виден покупателю на сайте', verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='customer_appropriate',
            field=models.BooleanField(default=False, help_text='виден покупателю на сайте', verbose_name='Показывать'),
        ),
    ]
