# Generated by Django 3.1.5 on 2023-11-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0025_auto_20231116_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeoption',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='ordering'),
        ),
    ]
