# Generated by Django 3.1.5 on 2022-08-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='signboards', verbose_name='image')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
    ]
