# Generated by Django 3.1.5 on 2022-09-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbersettings',
            options={'verbose_name': 'Настройки Сбера', 'verbose_name_plural': 'Настройки Сбера'},
        ),
        migrations.AddField(
            model_name='sbersettings',
            name='max_amount',
            field=models.IntegerField(default=10000, verbose_name='максимальная сумма заказа'),
        ),
        migrations.AddField(
            model_name='sbersettings',
            name='min_amount',
            field=models.IntegerField(default=500, verbose_name='минимальная сумма заказа'),
        ),
        migrations.AlterField(
            model_name='sbersettings',
            name='tax_system',
            field=models.CharField(choices=[('0', 'общая'), ('1', 'упрощённая, доход'), ('2', 'упрощённая, доход минус расход'), ('3', 'единый налог на вменённый доход'), ('4', 'единый сельскохозяйственный налог'), ('5', 'патентная система налогообложения')], max_length=1),
        ),
    ]
