# Generated by Django 3.1.5 on 2022-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя точки')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес точки')),
                ('volume', models.IntegerField(default=100, verbose_name='рубли')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
