# Generated by Django 3.1.5 on 2022-09-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/points', verbose_name='картинка'),
        ),
    ]
