# Generated by Django 3.1.5 on 2022-10-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_point_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='subnetwork',
            field=models.CharField(default='', max_length=10),
        ),
    ]
