# Generated by Django 3.1.5 on 2022-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Имя точки')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/main', verbose_name='картинка')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='menu_pictures',
            field=models.ManyToManyField(to='main.Image', verbose_name='картинки для меню'),
        ),
    ]
