# Generated by Django 3.1.5 on 2022-11-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221128_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.CharField(default='', max_length=200, verbose_name='slug картинки'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Имя картинки'),
        ),
    ]
