# Generated by Django 3.1.5 on 2022-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221128_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mobile',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
