# Generated by Django 3.1.5 on 2023-11-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mobile',
            field=models.BooleanField(default=False, verbose_name='mobile'),
        ),
    ]
